# Generated by Django 4.2.23 on 2025-07-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
